### PR TITLE
feat: eda plot view

### LINKED ISSUE #955: EDA: Plot view
### Is your feature request related to a problem?

Allow for plot views ideally before new project group needs it.

### Desired solution

Plot view with it's own tab in sidebar that displays generated plots like in wireframe.
Plot tabs can be created with column selections and then right click, the guided menu and by enlarging a profiling image.
For this the base history handling of data manipulative actions will have to be set up in webview and extension. In line with that, non data manipulative actions that already exist can be implemented into that too. The full history handling will come later, this is only to pave the way.

### Possible alternatives (optional)

_No response_

### Screenshots (optional)

_No response_

### Additional Context (optional)

_No response_

### LINKED ISSUE #986: EDA: Remove old vs-code states
### Is your feature request related to a problem?

Currently the global vs-code state fills up over time making certain operations slow.

### Desired solution

The goal is to save the Date of last update along with the State in the global state. Then in the findCurrentState method where those states are iterated once on a new panel startup anyway, the AST should be searched for the placeholder and pipeline name of the old states and in case it does not find that combination AND the states last update is more than a day ago, it should remove that state from the global state.

### Possible alternatives (optional)

Just remove if older than 7 days and do not care about the placeholder existence.

### Screenshots (optional)

_No response_

### Additional Context (optional)

_No response_

### PR DESCRIPTION
**Pull request by SmiteDeluxe**
Closes #955
Closes #986

### Summary of Changes

Implemented history/action structure for webview to add new actions to state and have them (if external and info not already present) send execute requests to runner that are then cancellable or deployed in correct order. Only fully working for Plots/Tabs at the moment, that are on deploy added to tabs state and set as currentIndex. All Tabs and Table retain their state. Runner uses existing methods in RunnerAPI to get back to relevant state by executing past manipulating actions and then returns the result of the new action (only if plots right now).

Tabs can be created by selecting columns and right clicking, zooming in on profiling images or by creating an empty tab with the plus icon in the sidebar. There in the guided menu users can change the current Tab to display other info. At that point the tab will go into building state and show prompts, loading screens and buttons accordingly. Typings are adapted to abstract as much as possible (mainly around column count for tabs, none, one and two) and stores are heavily used for reactivity.

### CODE REVIEW

**Comment by SmiteDeluxe** [comment]
@lars-reimann a note on this: Creating a boxplot on a non-numeric column throws an error. For other plots this works fine. Should I manually disallow boxplots for categorical columns (with my limited interpretation of categorical vs numerical atm) or is there smth to be done elsewhere?

**Comment by lars-reimann** [comment]
@SmiteDeluxe [ExperimentalDataType.is_numeric](https://library.safeds.com/en/stable/reference/safeds/data/tabular/typing/ExperimentalDataType/#safeds.data.tabular.typing.ExperimentalDataType.is_numeric) and [ExperimentalSchema](https://library.safeds.com/en/stable/reference/safeds/data/tabular/typing/ExperimentalSchema/) should help with this. I don't expect major changes to this other than dropping the prefix "Experimental" from the name.

**Comment by lars-reimann** [comment]
> @lars-reimann Will go wit the is_numeric then for now and disallow boxplots for other columns. Will do a new PR for that after this is merged!

Alright. I probably won't be able to review this PR before the weekend.

**Comment by lars-reimann** [comment]
Although, maybe I'll find time to review it tomorrow morning and do another release for the lab. Looks awesome at first glance!

**Comment by SmiteDeluxe** [comment]
@lars-reimann for this: [ExperimentalDataType.is_numeric](https://library.safeds.com/en/stable/reference/safeds/data/tabular/typing/ExperimentalDataType/#safeds.data.tabular.typing.ExperimentalDataType.is_numeric)

Do I need to define my own stubs?

**Comment by lars-reimann** [comment]
Nope, it's in the latest release.

**Review by lars-reimann — APPROVED** [review]
No suggestions, very nicely done!

**Pull request merged**
