### PR TITLE
feat(eda): filter by column

### LINKED ISSUE #1216: EDA: filter by column
### Is your feature request related to a problem?

Filter does not work.

### Desired solution

Filter that depending on data allows certain operations.
Profiling stored with history entries and if no profiling available for a step shows button to refresh it. History decides if to use profiling from entry before or say there is no up to date profiling (for now only if action was a filter).
Filters should make all visualizations that include them outdated.

### Possible alternatives (optional)

_No response_

### Screenshots (optional)

_No response_

### Additional Context (optional)

_No response_

### PR DESCRIPTION
**Pull request by SmiteDeluxe**
Closes #1216 

### Summary of Changes

Can now filter rows by columns.
Filters update and retain state. Profiling gets outdated depending on if current History state has profiling. Can get refreshed (that runner method inefficient since calling runner 3 times but not enough time). Tabs get set to outdated appropriately.
WARNING: Includes all other pending PRs, approve those first.

### CODE REVIEW

**Comment by SmiteDeluxe** [comment]
@lars-reimann all should be good to go now!

**Comment by SmiteDeluxe** [comment]
I know this last push fits more on the the other PR but was coding on this and then noticed on other branch there are conflicts, so just pushed here.

**Comment by SmiteDeluxe** [comment]
@lars-reimann this should be ready to merge!

**Comment by lars-reimann** [comment]
@SmiteDeluxe Please take a look at the linter failures.

**Pull request merged**
